### ISSUE TITLE
ndkpath.txt missing

### ISSUE THREAD

**Issue by Awsomeworld304** [Raemien/MRCPlus#1]
When I run any of the scrips to build the mod it tells me ndkpath.txt doesn't exist.

**Comment by Raemien** [comment]
Hi there!
The 'ndkpath.txt' file is intentionally excluded from the repository, as most people will have a different ndk directory.

If this is your first time working with Quest mods, I'd strongly recommend starting your own project first. It's a great learning experience. If you're unsure where to start, the BSMG discord server has a few guides that you may find helpful.

As much as I'd love to help with the building process, the mod is currently unreleased. Feel free to reach out to me on Discord once everything is ready for the public.
