### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by Honestlyi** [Raemien/MRCPlus#11]
Is there a way to see avatar at all?

**Comment by BoogieHasFun** [comment]
no, a mod is being created for that

**Comment by Raemien** [comment]
Hi there! Henwill8 was looking into decoupling Replay's multiplayer avatars into a mod accessible by MRCPlus some months ago, though this project may have since pivoted. There are now some very ambitious (and promising) alternatives in development, so you may want to keep an eye out for that.
