### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by ghost** [Raemien/MRCPlus#2]
The video quality is great! The only problems I am having is audio is cutting out and in and every once in a while, the game LAGS really bad. Other than that, GREAT job!

**Comment by Raemien** [comment]
Hi there!
It appears that you're using the game's existing MRC support.
While the mod is currently unreleased, [this guide](https://github.com/Raemien/MRCPlus/wiki/Common-Issues) may be useful for resolving non MRCPlus-related issues.
