### ISSUE TITLE
mrcplus seems to freeze game

### ISSUE THREAD

**Issue by mixedissmiling** [Raemien/MRCPlus#5]
So when setting up MRCPlus for the latest version, it seems to be freezing my bs, also, if possible, there might need to be some more optimizations as the game becomes very laggy while stream even with a lower res

**Comment by BoogieHasFun** [comment]
this happens will all mrc games, so this is a issue with mrc or your wifi

**Comment by mixedissmiling** [comment]
Oh okay

>
