### ISSUE TITLE
frames per second turns to seconds per frame

### ISSUE THREAD

**Issue by NikonUK** [Raemien/MRCPlus#6]
when i connect obs to my quest using mrcplus my quest lags so much that fps turns to spf

this is without using akiatweaks cause its not updated to latest yet

also im using gigabit ethernet so low speeds cant be the issue

**Comment by Raemien** [comment]
Hi there!
Would you be able to share which headset you're using? Previous performance testing with the Quest 1 and 2 suggests that both devices can hold a stable 72/90hz without the aid of AikaTweaks, though this seems to be a common issues.

There are a few troubleshooting steps you could follow such as moving your headset closer to your wireless access point. If you're able to host a wireless hotspot on your PC, this is highly recommended to reduce both latency and dropped packets.

Thanks for reporting the issue, I'd like to gather as much information as possible to document MRC's erratic behaviour.

**Comment by LordNikon005** [comment]
> Hi there!
> Would you be able to share which headset you're using? Previous performance testing with the Quest 1 and 2 suggests that both devices can hold a stable 72/90hz without the aid of AikaTweaks, though this seems to be a common issues.
> 
> There are a few troubleshooting steps you could follow such as moving your headset closer to your wireless access point. If you're able to host a wireless hotspot on your PC, this is highly recommended to reduce both latency and dropped packets.
> 
> Thanks for reporting the issue, I'd like to gather as much information as possible to document MRC's erratic behaviour.

**Comment by NikonUK** [comment]
hi. yeah im using a quest 2. also i was using a router i got that supports 5g (not wifi 6 sadge) with an ethernet cable to the back of my pc and my quest connected to that router. i have no clue what happened but ive somehow fixed it? if it happens again ill see if i can find out what the issue is
