### ISSUE TITLE
Audio not outputting in OBS?

### ISSUE THREAD

**Issue by mixedissmiling** [Raemien/MRCPlus#7]
So whenever I attempt to output audio with the audio fix (monitor only), it doesn’t output. And I know it’s not OBS  because I’ve used it with other sources

**Comment by Raemien** [comment]
Hi there! Did you check that your Audio Output source is set to the same device as the mirrored audio device?
You'll want to make sure both of these are set to the same audio device for OBS to pick it up.

From the Audio Output source panel:
![image](https://user-images.githubusercontent.com/39755457/139615818-b423ea83-34a3-4f5d-a5ba-fea1b8b9deff.png)

From the OBS Settings panel:
![image](https://user-images.githubusercontent.com/39755457/139615595-20f56a3a-ed71-47be-8015-98e0ac2160c6.png)

**Comment by mixedissmiling** [comment]
As far as I can remember it is, I can check again though

**Comment by mixedissmiling** [comment]
it is now, ill try it out to see if it works in a bit

**Comment by mixedissmiling** [comment]
Honestly, I have no idea how, but it’s fixed! Thank you very much!
