### ISSUE TITLE
MRCPlus Crashes when installed and enabled with Noodle

### ISSUE THREAD

**Issue by mixedissmiling** [Raemien/MRCPlus#9]
When selecting a map with MRCPlus and Noodle enabled Beat Saber seems to crash

**Comment by BoogieHasFun** [comment]
thats not true, i played a noodle map with mrcplus enabled and outputting video & audio.
test using mrcplus and noodle as the only mods enabled (expect core mods of course)

**Comment by Raemien** [comment]
Have you checked whether Mapping Extensions is enabled? I've personally never come across this behaviour with MRCPlus in many months of in-dev testing. You may need to uninstall some other mods (Chroma, ME, Technicolor, etc) and reinstall Noodle Extensions if this issue persists.

**Comment by mixedissmiling** [comment]
Yeah, I’m pretty sure scribble and Technicolor was the issue, thanks!

**Comment by Raemien** [comment]
No worries!
